[package]
name = "remote_waker"
version = "1.0.0"
edition = "2021"
description = "A library to wake tasks remotely"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
